#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#pragma comment(lib, "Ws2_32.lib")

#include <stdio.h>
#include <string.h>

typedef enum { TRNS_FAILED, TRNS_DISCONNECTED, TRNS_SUCCEEDED } TransferResult_t;

#define STATUS_CODE_FAILURE -1
#define STATUS_CODE_SUCCESS 0

// Server Messages
#define SERVER_MAIN_MENU "SERVER_MAIN_MENU"
#define SERVER_APPROVED "SERVER_APPROVED"
#define SERVER_DENIED "SERVER_DENIED"
#define SERVER_INVITE "SERVER_INVITE"
#define SERVER_PLAYER_MOVE_REQUEST "SERVER_PLAYER_MOVE_REQUEST"
#define SERVER_GAME_RESULTS "SERVER_GAME_RESULTS"
#define SERVER_GAME_OVER_MENU "SERVER_GAME_OVER_MENU"
#define SERVER_OPPONENT_QUIT "SERVER_OPPONENT_QUIT"
#define SERVER_NO_OPPONENTS "SERVER_NO_OPPONENTS"
#define SERVER_LEADERBOARD "SERVER_LEADERBOARD"
#define SEND_STR_MAX_SIZE 
#define USERNAME_MAX_LENGTH 20